#!/bin/sh
set -e

CONFIG=/data/stash-server.toml

# The interactive setup wizard binds on a random localhost port, which is not
# reachable from outside the container. Require STASH_PASSWORD instead.
if [ ! -f "$CONFIG" ] && [ -z "$STASH_PASSWORD" ]; then
    echo ""
    echo "ERROR: No config found at $CONFIG and STASH_PASSWORD is not set."
    echo ""
    echo "Set the STASH_PASSWORD environment variable to configure the server:"
    echo "  docker run -e STASH_PASSWORD=yourpassword ..."
    echo "  # or in compose.yml:  environment: - STASH_PASSWORD=yourpassword"
    echo ""
    exit 1
fi

# First run: if STASH_PASSWORD is set and no config exists yet, create a minimal
# config with Docker-friendly defaults (web UI accessible on all interfaces).
if [ ! -f "$CONFIG" ] && [ -n "$STASH_PASSWORD" ]; then
    cat > "$CONFIG" <<'EOF'
# Stash server config — auto-generated by Docker entrypoint.
# Edit this file to configure TLS, mirror sync, max file size, etc.
# See the README for all available options.

# Expose the web UI on all interfaces so it's reachable from the host.
# Remove or change to "127.0.0.1:9877" to restrict access.
web_bind = "0.0.0.0:9877"
EOF
fi

# Write/update the password hash (idempotent — safe to run on every start).
if [ -n "$STASH_PASSWORD" ]; then
    stash-server --config "$CONFIG" set-password --password "$STASH_PASSWORD"
fi

# Pass --data-dir explicitly so the wizard (if it ever runs) also uses the volume.
# Any extra CMD arguments are forwarded (e.g. --bind, --password-hash).
exec stash-server --config "$CONFIG" --data-dir /data "$@"
